<?xml version="1.0"?>
<robot name="two_wheel_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="chassis_x" value="0.30"/>
  <xacro:property name="chassis_y" value="0.22"/>
  <xacro:property name="chassis_z" value="0.08"/>

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>

  <xacro:property name="wheel_x" value="-0.10"/>
  <xacro:property name="wheel_y" value="0.11"/>

  <material name="gray">
    <color rgba="0.6 0.6 0.6 1"/>
  </material>

  <material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>

  <link name="world"/>
  <link name="odom"/>
  <link name="base_footprint"/>

  <joint name="world_to_odom" type="fixed">
    <parent link="world"/>
    <child link="odom"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="odom_to_base_footprint" type="fixed">
    <parent link="odom"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="base_footprint_to_base_link" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${chassis_z/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_x} ${chassis_y} ${chassis_z}"/>
      </geometry>
      <material name="gray"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${chassis_z/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_x} ${chassis_y} ${chassis_z}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${chassis_z/2}" rpy="0 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.02" ixy="0.0" ixz="0.0"
               iyy="0.03" iyz="0.0"
               izz="0.04"/>
    </inertial>
  </link>

  <xacro:macro name="wheel" params="name parent xyz">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.0005" ixy="0.0" ixz="0.0"
                 iyy="0.0008" iyz="0.0"
                 izz="0.0005"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${name}_link"/>
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1" friction="0.2"/>
    </joint>
  </xacro:macro>

  <xacro:wheel name="left_wheel" parent="base_link"
               xyz="${wheel_x} ${wheel_y} ${wheel_radius}"/>

  <xacro:wheel name="right_wheel" parent="base_link"
               xyz="${wheel_x} -${wheel_y} ${wheel_radius}"/>

</robot>